# docker-enginge: 17.06.0+
# docker-compose.yml preferes spaces over tabs

version: '3.3'

services:

  alpine.ansible.app:
    container_name: alpine.ansible.app
    volumes:
        - ./app:/var/www/app/
    build:
        labels:
            alpine.ansible.app.description: "template for boilerplate"
        
        context: ./
        dockerfile: ./dockerfiles/docker.alpine.ansible.sh
        
    command: "ansible-playbook --version"
    
    image: researchranks/alpine.ansible:latest

    expose:
        - 8080

    ports:
        - 80:8080
